templates:
  find_text_scroll: &find_text_scroll
    action: FIND
    object_type: TEXT
    click: True
    scroll: True
    scroll_image_path: $SCROLL_PATH

  find_img_scroll: &find_img_scroll
    action: FIND
    object_type: IMG
    click: True
    scroll: True
    scroll_image_path: $SCROLL_PATH


pipelines:
  login:
    url: $URL
    steps:
      - <<: *find_img_scroll
        image_path: $IMG_DIR/login_pipeline/username.png
      - action: WRITE
        text: $USERNAME
      - <<: *find_img_scroll
        image_path: $IMG_DIR/login_pipeline/password.png
      - action: WRITE
        text: $PASSWORD
      - <<: *find_img_scroll
        image_path: $IMG_DIR/login_pipeline/login_button.png
        wait: 1

        
  scroll_test:
    steps:
      - <<: *find_img_scroll
        image_path: $IMG_DIR/dataset_pipeline/dataset_button.png
        wait: 0.5
      - <<: *find_text_scroll
        text: "NAO EXISTO"
