

services:
  # docker compose up api --build
  api:
    build:
      context: .
      dockerfile: BotUi_Setup/Dockerfile.api
    container_name: botui_api
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - botui_network
    environment:
      - BOTUI_ENV=dev
      - DOCKER_NETWORK=botui_network
      - BOTUI_IMAGE=botui
      - BOT_PATH="/app/bot/"
  
  # docker compose up dashboard --build
  dashboard: 
    build:
      context: .
      dockerfile: BotUi_Setup/Dockerfile.app
    container_name: botui_app
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    networks:
      - botui_network

networks:
  botui_network:
    name: botui_network