FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y docker-cli

COPY packages/botui-manager /app/packages/botui-manager

RUN pip install --no-cache-dir -e /app/packages/botui-manager

EXPOSE 8000

CMD ["uvicorn", "BotUiManager.api.main:app", "--host", "0.0.0.0", "--port", "8000"]