pipelines:
  google_consent:
    url: $URL
    steps:
      - action: FIND
        object_type: TEXT
        text: "Consent"
        optional: True
        click: True

  
  login:
    steps:
      - action: FIND
        object_type: TEXT
        text: "Choose name"
        click: True
      - action: FIND
        object_type: TEXT
        text: "Username"
        y_coord: 2
        click: True
      - action: WRITE
        text: $USERNAME
      - action: FIND
        object_type: TEXT
        text: "Choose name"
        click: True
        position: 1
      - action: FIND
        object_type: TEXT
        text: "Password"
        y_coord: 2
        click: True
      - action: WRITE
        text: $PASSWORD
      - action: KEYS_SELECTIONS
        keys:
          - ENTER
      - action: FIND
        object_type: TEXT
        text: $USERNAME
        until_find: retry
        helper: "Tentando localizar nome logado!"
        

  game_mode:
    steps:
      - action: FIND
        object_type: TEXT
        text: "Format"
        y_coord: 20
        click: true
      
      - action: FIND
        object_type: TEXT
        text: "Randomized Metas"
        click: true
        x_coord: -10

      - action: FIND
        object_type: TEXT
        text: "Challenge Cup 1v1"
        click: true
        debug: true

      - action: FIND
        object_type: TEXT
        text: "Battle!"
        click: true
        wait: 0.2

      - action: FIND
        object_type: TEXT
        text: "Connecting..."
        optional: true
      
      - action: FIND
        object_type: TEXT
        text: "Cancel"
        debug: true
        click: true



# challenge cup 1 v 1

# Se encontrar "Rematch" -> Acabou!