pipelines:
  main:
    url: $URL
    steps:
      - action: IMPORT_ACTIONS
        path: action_group/login.yaml
      


      # --------------------------------
      # CHECK IF IS BATTLEING
      # --------------------------------
      - action: FIND
        name: check_if_is_battling
        object_type: TEXT
        text: "Choose"
        in_text: True
        debug: True
        interaction:
          type: CLICK  
        search_area:
          row: 1
          column: 0
          grid_rows: 3    
          grid_cols: 3
        next:
          true: apologies
          false: find_format_box


      # --------------------------------
      # IF IS NOT BATTLEING
      # --------------------------------
      - action: IMPORT_ACTIONS
        path: action_group/gamemode.yaml

      # --------------------------------
      # IF IS BATTLEING
      # --------------------------------
      - action: IMPORT_ACTIONS
        path: action_group/1v1_challenge_cup.yaml


      # --------------------------------
      # END
      # --------------------------------

      - action: STOP_IF
        name: end
        condition: "True"







# Se encontrar "Rematch" -> Acabou!

# COMMANDS: /report, /msg, /reply, /logout, /challenge, /search, /rating, /whois, /user, /join, /leave, /userauth, /roomauth
# BATTLE ROOM COMMANDS: /savereplay, /hideroom, /inviteonly, /invite, /timer, /forfeit
# OPTION COMMANDS: /nick, /avatar, /ignore, /status, /away, /busy, /back, /timestamps, /highlight, /showjoins, /hidejoins, /blockchallenges, /blockpms
# INFORMATIONAL/RESOURCE COMMANDS: /groups, /faq, /rules, /intro, /formatshelp, /othermetas, /analysis, /punishments, /calc, /git, /cap, /roomhelp, /roomfaq (replace / with ! to broadcast. Broadcasting requires: + % @ # ~)
# DATA COMMANDS: /data, /dexsearch, /movesearch, /itemsearch, /learn, /statcalc, /effectiveness, /weakness, /coverage, /randommove, /randompokemon (replace / with ! to broadcast. Broadcasting requires: + % @ # ~)