pipelines:
  google_consent:
    url: $URL
    steps:
      - action: FIND
        object_type: TEXT
        text: "Consent"
        optional: True
        click: True

  
  login:
    steps:
      - action: FIND
        object_type: TEXT
        text: "Choose name"
        click: True
      - action: FIND
        object_type: TEXT
        text: "Username"
        y_coord: 2
        click: True
      - action: WRITE
        text: $USERNAME
      - action: FIND
        object_type: TEXT
        text: "Choose name"
        click: True
        position: 1
      - action: FIND
        object_type: TEXT
        text: "Password"
        y_coord: 2
        click: True
      - action: WRITE
        text: $PASSWORD
      - action: KEYS_SELECTIONS
        keys:
          - ENTER
      - action: FIND
        object_type: TEXT
        text: $USERNAME
        until_find: retry
        helper: "Tentando localizar nome logado!"
        

  game_mode:
    steps:
      - action: FIND
        object_type: TEXT
        text: "Format"
